// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: cluster.proto

package clusterpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_Register_FullMethodName        = "/cluster.v1.NodeService/Register"
	NodeService_Heartbeat_FullMethodName       = "/cluster.v1.NodeService/Heartbeat"
	NodeService_GetAssignments_FullMethodName  = "/cluster.v1.NodeService/GetAssignments"
	NodeService_UpdateJobStatus_FullMethodName = "/cluster.v1.NodeService/UpdateJobStatus"
	NodeService_StreamLogs_FullMethodName      = "/cluster.v1.NodeService/StreamLogs"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeService is implemented by the scheduler and called by node agents. Agents
// register, heartbeat their health/usage, poll for job assignments, report job
// status transitions, and stream execution logs back to the control plane.
type NodeServiceClient interface {
	// Register announces a node (or re-announces it after a restart) with its
	// total capacity.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Heartbeat reports liveness and current live resource availability. Missing
	// heartbeats cause the node to be marked down and its jobs rescheduled.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// GetAssignments returns jobs the scheduler has placed on this node that the
	// agent has not yet started.
	GetAssignments(ctx context.Context, in *AssignmentsRequest, opts ...grpc.CallOption) (*AssignmentsResponse, error)
	// UpdateJobStatus reports a job lifecycle transition (running/completed/failed).
	UpdateJobStatus(ctx context.Context, in *JobStatusUpdate, opts ...grpc.CallOption) (*Ack, error)
	// StreamLogs is a client-streaming RPC the agent uses to ship job log lines to
	// the control plane, where recent lines are cached for the API.
	StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogLine, Ack], error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, NodeService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, NodeService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetAssignments(ctx context.Context, in *AssignmentsRequest, opts ...grpc.CallOption) (*AssignmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignmentsResponse)
	err := c.cc.Invoke(ctx, NodeService_GetAssignments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) UpdateJobStatus(ctx context.Context, in *JobStatusUpdate, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, NodeService_UpdateJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogLine, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[0], NodeService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogLine, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StreamLogsClient = grpc.ClientStreamingClient[LogLine, Ack]

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
//
// NodeService is implemented by the scheduler and called by node agents. Agents
// register, heartbeat their health/usage, poll for job assignments, report job
// status transitions, and stream execution logs back to the control plane.
type NodeServiceServer interface {
	// Register announces a node (or re-announces it after a restart) with its
	// total capacity.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Heartbeat reports liveness and current live resource availability. Missing
	// heartbeats cause the node to be marked down and its jobs rescheduled.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// GetAssignments returns jobs the scheduler has placed on this node that the
	// agent has not yet started.
	GetAssignments(context.Context, *AssignmentsRequest) (*AssignmentsResponse, error)
	// UpdateJobStatus reports a job lifecycle transition (running/completed/failed).
	UpdateJobStatus(context.Context, *JobStatusUpdate) (*Ack, error)
	// StreamLogs is a client-streaming RPC the agent uses to ship job log lines to
	// the control plane, where recent lines are cached for the API.
	StreamLogs(grpc.ClientStreamingServer[LogLine, Ack]) error
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedNodeServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedNodeServiceServer) GetAssignments(context.Context, *AssignmentsRequest) (*AssignmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssignments not implemented")
}
func (UnimplementedNodeServiceServer) UpdateJobStatus(context.Context, *JobStatusUpdate) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateJobStatus not implemented")
}
func (UnimplementedNodeServiceServer) StreamLogs(grpc.ClientStreamingServer[LogLine, Ack]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetAssignments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetAssignments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetAssignments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetAssignments(ctx, req.(*AssignmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_UpdateJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobStatusUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).UpdateJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_UpdateJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).UpdateJobStatus(ctx, req.(*JobStatusUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeServiceServer).StreamLogs(&grpc.GenericServerStream[LogLine, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StreamLogsServer = grpc.ClientStreamingServer[LogLine, Ack]

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cluster.v1.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _NodeService_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _NodeService_Heartbeat_Handler,
		},
		{
			MethodName: "GetAssignments",
			Handler:    _NodeService_GetAssignments_Handler,
		},
		{
			MethodName: "UpdateJobStatus",
			Handler:    _NodeService_UpdateJobStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _NodeService_StreamLogs_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "cluster.proto",
}
